services:
  - type: web
    name: cozystudy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ROOM_PASSWORD
        value: Sezen99720.
